name: NewTBS/TBS-API-Dev
on:
  push:
    branches:
    - Development
    - prod/TBS-prod
env:
  BuildConfiguration: release
  BuildPlatform: any cpu
  system_debug: 'false'
jobs:
  Job_1:
    name: Agent job 1
    runs-on: windows-2019
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - name: NuGet restore
      run: nuget restore TimeSystemServerModule/TimeSystemServerModule/TimeSystemServerApi.csproj -Verbosity "Detailed"
    - name: install msbuild
      uses: microsoft/setup-msbuild@v1.1.3
    - name: run msbuild
      run: msbuild TimeSystemServerModule/TimeSystemServerModule.sln /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{ runner.temp }}\\" -p:Configuration=${{ env.BuildConfiguration }} -p:Platform="${{ env.BuildPlatform }}  " -v:normal
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v3.1.1
      with:
        name: drop
        path: "${{ runner.temp }}"
